# Generated by Django 3.0.5 on 2020-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0002_auto_20200617_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproyecto',
            name='url',
            field=models.TextField(default='proyectos'),
        ),
    ]
