# Generated by Django 3.0.5 on 2020-06-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JIT', '0003_tipoproyecto_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tipoproyecto',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='tipoproyecto',
            name='public',
        ),
        migrations.RemoveField(
            model_name='tipoproyecto',
            name='url',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='JIT.TipoProyecto', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='content',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen PC'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imageM',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen Móvil'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imaget',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen Tablet'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='public',
            field=models.BooleanField(verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.URLField(verbose_name='URL de la página web'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='content',
            field=models.TextField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
