# Generated by Django 3.0.5 on 2020-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0005_auto_20200617_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='category',
            field=models.ManyToManyField(to='JIT.TipoProyecto', verbose_name='Categoría'),
        ),
    ]
