# Generated by Django 3.0.5 on 2020-06-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0006_auto_20200617_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='tipoproyecto',
            name='updated_at',
        ),
    ]
