# Generated by Django 3.0.5 on 2020-06-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0007_auto_20200617_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categories',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoProyecto', verbose_name='Categoría'),
        ),
    ]
