# Generated by Django 3.0.5 on 2020-06-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0009_equipo_servicio_tiposervicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoProyecto', verbose_name='Categoría Proyecto'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoProyecto', verbose_name='Categoría Servicio'),
        ),
    ]
