# Generated by Django 3.0.5 on 2020-06-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0010_auto_20200618_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproyecto',
            options={'verbose_name': 'Categoría Proyecto', 'verbose_name_plural': 'Categorías Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'verbose_name': 'Categoría Servicio', 'verbose_name_plural': 'Categorías Servicio'},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='categories',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoServicio', verbose_name='Categoría Servicio'),
        ),
    ]
