# Generated by Django 3.0.5 on 2020-06-18 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0011_auto_20200618_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('public', models.BooleanField(verbose_name='¿Público?')),
                ('image', models.ImageField(default='null', upload_to='Noticias', verbose_name='Imagen tarjeta')),
                ('url', models.URLField(verbose_name='URL de la noticia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Paso_filosofia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('public', models.BooleanField(verbose_name='¿Público?')),
                ('image', models.ImageField(default='null', upload_to='Filosofia', verbose_name='Imagen ícono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
            ],
            options={
                'verbose_name': 'Paso Filosofía',
                'verbose_name_plural': 'Pasos Filosofías',
            },
        ),
        migrations.CreateModel(
            name='Post_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción de la tarjeta')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido del Post')),
                ('public', models.BooleanField(verbose_name='¿Público?')),
                ('image', models.ImageField(default='null', upload_to='Noticias', verbose_name='Imagen')),
                ('url', models.URLField(verbose_name='URL de la noticia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha modificado')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
                ('content', models.TextField(max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría Noticia',
                'verbose_name_plural': 'Categorías Noticia',
            },
        ),
    ]
