# Generated by Django 3.0.5 on 2020-06-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0012_noticia_paso_filosofia_post_blog_tiponoticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoNoticia', verbose_name='Categoría Servicio'),
        ),
        migrations.AddField(
            model_name='post_blog',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIT.TipoNoticia', verbose_name='Categoría Servicio'),
        ),
    ]
