# Generated by Django 3.0.5 on 2020-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0014_auto_20200618_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponoticia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificado'),
        ),
        migrations.AddField(
            model_name='tipoproyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificado'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificado'),
        ),
        migrations.AlterField(
            model_name='tiponoticia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
    ]
