# Generated by Django 3.0.5 on 2020-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0015_auto_20200618_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproyecto',
            name='image',
            field=models.FileField(default='null', upload_to='Proyectos'),
        ),
    ]
