# Generated by Django 3.0.5 on 2020-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0016_auto_20200619_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproyecto',
            name='image',
            field=models.ImageField(default='null', upload_to='Proyectos'),
        ),
    ]
