# Generated by Django 3.0.5 on 2020-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0019_auto_20200619_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='app',
            field=models.BooleanField(null=True, verbose_name='Marcar SOLO si es una app'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen PC/(Imagen 1 para APP)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imageM',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen Móvil/(Imagen 2 para APP)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imaget',
            field=models.ImageField(default='null', upload_to='Proyectos', verbose_name='Imagen Tablet/(Imagen 3 para APP)'),
        ),
    ]
