# Generated by Django 3.0.5 on 2020-06-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0021_auto_20200620_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL de la página web'),
        ),
    ]
