# Generated by Django 3.0.5 on 2020-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0022_auto_20200620_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso_filosofia',
            name='image',
            field=models.FileField(default='null', upload_to='Filosofia', verbose_name='Imagen ícono'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.FileField(default='null', upload_to='Servicio', verbose_name='Imagen'),
        ),
    ]
