# Generated by Django 3.0.5 on 2020-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0023_auto_20200620_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso_filosofia',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden de aparición(Uno ha de estar a cero)'),
        ),
    ]
