# Generated by Django 3.0.5 on 2020-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0024_paso_filosofia_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='image',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
