# Generated by Django 3.0.5 on 2020-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0025_auto_20200621_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponoticia',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AddField(
            model_name='tipoproyecto',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='paso_filosofia',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='public',
            field=models.BooleanField(default=False, verbose_name='¿Público?'),
        ),
    ]
