# Generated by Django 3.0.5 on 2020-06-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0026_auto_20200621_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproyecto',
            name='slug',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slug de la URL'),
        ),
    ]
