# Generated by Django 3.0.5 on 2020-06-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0027_tipoproyecto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.FileField(default='null', upload_to='', verbose_name='Imagen PC/(Imagen 1 para APP)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imageM',
            field=models.ImageField(default='null', upload_to='', verbose_name='Imagen Móvil/(Imagen 2 para APP)'),
        ),
    ]
