# Generated by Django 3.0.5 on 2020-06-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0029_tiposervicio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='image',
            field=models.FileField(default='null', upload_to='Equipo', verbose_name='Imagen ícono'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='image_perfil',
            field=models.FileField(default='null', upload_to='Equipo', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.FileField(default='null', upload_to='Noticias', verbose_name='Imagen tarjeta'),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='image',
            field=models.FileField(default='null', upload_to='Noticias', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imageM',
            field=models.FileField(default='null', upload_to='', verbose_name='Imagen Móvil/(Imagen 2 para APP)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imaget',
            field=models.FileField(default='null', upload_to='Proyectos', verbose_name='Imagen Tablet/(Imagen 3 para APP)'),
        ),
    ]
