# Generated by Django 3.0.5 on 2020-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0030_auto_20200621_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descripción pagina'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='frase',
            field=models.CharField(blank=True, max_length=300, verbose_name='Frase en página'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='frase2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Frase2 en página'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='frase3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Frase3 en página'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo en página'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='content',
            field=models.TextField(max_length=255, verbose_name='Descripción tarjeta'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre tarjeta'),
        ),
    ]
