# Generated by Django 3.0.5 on 2020-06-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0031_auto_20200621_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervicio',
            name='subtitle',
        ),
    ]
