# Generated by Django 3.0.5 on 2020-06-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0032_remove_tiposervicio_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='user',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='content',
            field=models.TextField(verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
