# Generated by Django 3.0.5 on 2020-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0033_auto_20200621_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='order',
            field=models.IntegerField(default=3, verbose_name='Orden de aparición'),
        ),
    ]
