# Generated by Django 3.0.5 on 2020-06-22 06:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0038_noticia_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='entry',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido de la entrada'),
        ),
        migrations.DeleteModel(
            name='Post_blog',
        ),
    ]
