# Generated by Django 3.0.5 on 2020-06-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0039_auto_20200622_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL de la noticia'),
        ),
    ]
