# Generated by Django 3.0.5 on 2020-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0040_auto_20200622_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='INICIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'INICIO',
                'verbose_name_plural': 'INICIO',
            },
        ),
    ]
