# Generated by Django 3.0.5 on 2020-06-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0041_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INICIO',
        ),
    ]
