# Generated by Django 3.0.5 on 2020-06-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0045_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción pagina'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='frase',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Frase en página'),
        ),
    ]
