# Generated by Django 3.0.5 on 2020-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0046_auto_20200626_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Título'),
        ),
    ]
