# Generated by Django 3.0.5 on 2020-07-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0048_proyecto_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
    ]
