# Generated by Django 3.0.5 on 2020-06-19 11:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Slug de la URL'),
        ),
    ]
