# Generated by Django 3.0.5 on 2020-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200619_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=10, verbose_name='Lenguaje'),
        ),
    ]
