# Generated by Django 3.0.5 on 2020-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200619_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='frase',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
    ]
