# Generated by Django 3.0.5 on 2020-06-25 08:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
    ]
